#!/usr/bin/env python3
"""每日 ip-radar-blocklist 推文:top_100.csv 分析 → 表格附图 → X API 发布。

管线位置:ipradar-blocklist.service 的第二行 ExecStartPost(push.sh 发布
Release 成功后运行)。因果顺序由 systemd 保证:导出失败 → 不发推;
推文永远指向当天已发布的 Release。

关键约定:
- 日期口径 = 北京日期(+08:00 固定偏移,中国无夏令时),与 push.sh 的
  RELEASE_DATE / tag vYYYY-MM-DD 严格一致。
- 防重:state 文件首 token = 已发推的北京日期;同日重复触发 exit 0。
- 失败:重试一次(默认等 600s),两次都败 → exit 1(journal 可见,
  不影响已完成的 Release)。
- 凭证:/root/.config/ipradar-tweet.json(root only,0600),绝不进仓库、
  绝不打日志。

用法:
  tweet.py --dry [--repo DIR] [--out PNG]   # 只出文案+图,不碰 API
  tweet.py [--repo DIR]                     # 正式发布(查 state、传图、发推)
"""
import argparse
import csv
import json
import os
import re
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO_DIR = Path(os.environ.get("BLOCKLIST_REPO_DIR", "/opt/ip-radar-blocklist"))
CREDS_PATH = Path(os.environ.get("X_CREDS", "/root/.config/ipradar-tweet.json"))
STATE_PATH = Path(os.environ.get("TWEET_STATE", "/var/lib/ipradar-blocklist/last-tweet"))
RETRY_DELAY_S = int(os.environ.get("TWEET_RETRY_S", "600"))

CSV_URL = "github.com/steponeerror/ip-radar-blocklist/releases/latest/download/top_100.csv"
REPO_URL = "github.com/steponeerror/ip-radar-blocklist"
FOOTER_TEXT = "generated by ip-radar · " + REPO_URL
HASHTAGS = "#cybersecurity #Infosec"
# 'blacklist'/'abuse-reports' 是溯源标签而非威胁类型,恒居榜首,剔除后再取 top3
_CLASS_EXCLUDE = {"blacklist", "abuse-reports"}
BEIJING = timezone(timedelta(hours=8))
MAX_WEIGHTED_LEN = 280
TOP_ROWS = 10

# ---------------------------------------------------------------- 文案

def flag(code: str) -> str:
    """两位国家码 → 国旗 emoji;非法/缺失返回空串。"""
    if len(code) == 2 and code.isalpha() and code.isupper():
        return chr(0x1F1E6 + ord(code[0]) - ord("A")) + chr(0x1F1E6 + ord(code[1]) - ord("A"))
    return ""


def weighted_len(text: str) -> int:
    """X 的字符口径:任何 URL 按 t.co 定长 23 计,其余按 UTF-16 码元。"""
    text = re.sub(r"(?:https?://|www\.)\S+|github\.com/\S+", "x" * 23, text)
    return len(text.encode("utf-16-le")) // 2


def beijing_today(now=None) -> str:
    dt = now.astimezone(BEIJING) if now else datetime.now(BEIJING)
    return dt.strftime("%Y-%m-%d")


def date_label(today: str) -> str:
    dt = datetime.strptime(today, "%Y-%m-%d")
    return f"{dt.strftime('%b')} {dt.day}"


def compute_stats(rows) -> dict:
    countries, classes = {}, {}
    confs = []
    for r in rows:
        countries[r["country"]] = countries.get(r["country"], 0) + 1
        for c in filter(None, (s.strip() for s in r["classes"].split(";"))):
            classes[c] = classes.get(c, 0) + 1
        confs.append(float(r["confidence"]))
    top_cc = sorted(countries.items(), key=lambda kv: (-kv[1], kv[0]))[:3]
    top_cls = sorted(((k, v) for k, v in classes.items() if k not in _CLASS_EXCLUDE),
                     key=lambda kv: (-kv[1], kv[0]))[:3]
    return {
        "countries": top_cc,
        "classes": top_cls,
        "avg_conf": round(sum(confs) / len(confs)) if confs else 0,
    }


def compose_text(stats: dict, pool_total, label: str) -> str:
    cc = " · ".join(f"{flag(c) or ''} {c} {n}".strip() for c, n in stats["countries"])
    cls = " · ".join(f"{k} {v}" for k, v in stats["classes"])
    pool = f"{pool_total:,}" if isinstance(pool_total, int) else str(pool_total)
    return (f"🛡️ ip-radar daily blocklist — {label}\n\n"
            f"{cc}\n"
            f"{cls} · avg conf {stats['avg_conf']}/100\n"
            f"Tracking {pool} malicious IPs\n\n"
            f"CSV: {CSV_URL}\n"
            f"Repo: {REPO_URL}\n"
            f"Data: ip-radar consensus engine\n\n"
            f"{HASHTAGS}")


# ---------------------------------------------------------------- 附图

def _char_w(font) -> int:
    """等宽字符宽度:Pillow ≥10 删除了 getsize,7.x 无 getbbox — 两头兼容。"""
    if hasattr(font, "getsize"):
        return font.getsize("M")[0]
    box = font.getbbox("M")
    return box[2] - box[0]


def render_table(rows, out_path: Path) -> None:
    """前 TOP_ROWS 行 × 8 列,暗色终端风。Pillow 7+ 兼容(不依赖 8.0 API)。"""
    from PIL import Image, ImageDraw, ImageFont  # 延迟导入:文案测试无需 PIL

    font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
    font_bold = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
    if not Path(font_path).exists():  # 退化:Windows/其他环境(仅本地开发用)
        font_path, font_bold = None, None
    body = ImageFont.truetype(font_path, 18) if font_path else ImageFont.load_default()
    head = ImageFont.truetype(font_bold, 17) if font_bold else body
    foot = ImageFont.truetype(font_path, 15) if font_path else body

    BG, PANEL, ROW_ALT = (13, 17, 23), (22, 27, 34), (17, 23, 30)
    GREEN, TEXT, DIM, SEP = (63, 185, 80), (201, 209, 217), (139, 148, 158), (48, 54, 61)
    cols = [("ip", lambda r: r["ip"]), ("asn", lambda r: r["asn"]),
            ("cc", lambda r: r["country"]), ("classes", lambda r: r["classes"]),
            ("conf", lambda r: r["confidence"]), ("src", lambda r: r["source_count"]),
            ("first_seen", lambda r: r["first_seen"][:10]), ("last_seen", lambda r: r["last_seen"][:10])]
    shown = rows[:TOP_ROWS]
    widths = [max(len(h), max((len(get(r)) for r in shown), default=0)) for h, get in cols]

    char_w = _char_w(body)
    gap, margin_x, pad_y, row_h, head_h = 3 * char_w, 24, 14, 34, 36
    img_w = margin_x * 2 + sum(w * char_w for w in widths) + gap * (len(cols) - 1)
    foot_h = 44
    img_h = pad_y + head_h + row_h * len(shown) + foot_h
    img = Image.new("RGB", (img_w, img_h), BG)
    d = ImageDraw.Draw(img)

    x = margin_x
    for (h, _), w in zip(cols, widths):
        d.text((x, pad_y + 8), h, font=head, fill=GREEN)
        x += w * char_w + gap
    d.rectangle([margin_x - 6, pad_y + head_h - 4, img_w - margin_x + 6, pad_y + head_h - 2], fill=SEP)

    y = pad_y + head_h
    for i, r in enumerate(shown):
        if i % 2:
            d.rectangle([0, y, img_w, y + row_h], fill=ROW_ALT)
        x = margin_x
        for (_, get), w in zip(cols, widths):
            d.text((x, y + 8), get(r), font=body, fill=TEXT)
            x += w * char_w + gap
        y += row_h

    d.rectangle([margin_x - 6, y + 10, img_w - margin_x + 6, y + 11], fill=SEP)
    d.text((margin_x, y + 20), FOOTER_TEXT, font=foot, fill=DIM)
    img.save(out_path, "PNG")


# ---------------------------------------------------------------- 发布

class TwitterError(RuntimeError):
    pass


def post_tweet(text: str, image_path: Path, creds: dict) -> str:
    """传图 + 发推,成功返回 tweet id。任何 >=400 视为失败。"""
    import requests
    from requests_oauthlib import OAuth1

    auth = OAuth1(creds["consumer_key"], creds["consumer_secret"],
                  creds["access_token"], creds["access_token_secret"])
    with open(image_path, "rb") as f:
        up = requests.post("https://upload.twitter.com/1.1/media/upload.json",
                           auth=auth, files={"media": f}, timeout=120)
    if up.status_code != 200:
        raise TwitterError(f"media upload HTTP {up.status_code}: {up.text[:200]}")
    media_id = up.json()["media_id_string"]

    resp = requests.post("https://api.x.com/2/tweets", auth=auth, timeout=30,
                         json={"text": text, "media": {"media_ids": [media_id]}})
    if resp.status_code not in (200, 201):
        raise TwitterError(f"tweet HTTP {resp.status_code}: {resp.text[:200]}")
    return str(resp.json()["data"]["id"])


# ---------------------------------------------------------------- 主流程

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=str(REPO_DIR), help="含 top_100.csv/manifest.json 的目录")
    ap.add_argument("--dry", action="store_true", help="只出文案+图,不碰 API")
    ap.add_argument("--out", default="/tmp/ipradar_tweet.png", help="附图输出路径")
    args = ap.parse_args()

    repo = Path(args.repo)
    rows = list(csv.DictReader(open(repo / "top_100.csv")))
    if not rows:
        print("[tweet] top_100.csv 为空 — 放弃", file=sys.stderr)
        return 1
    pool = json.load(open(repo / "manifest.json")).get("malicious_pool")

    today = beijing_today()
    text = compose_text(compute_stats(rows), pool, date_label(today))
    wl = weighted_len(text)
    print(f"[tweet] 文案(加权 {wl}/{MAX_WEIGHTED_LEN} 字符):\n{text}\n")
    if wl > MAX_WEIGHTED_LEN:
        print("[tweet] 文案超长 — 放弃(检查列宽/类名异常)", file=sys.stderr)
        return 1

    out = Path(args.out)
    render_table(rows, out)
    print(f"[tweet] 附图: {out} ({out.stat().st_size} bytes)")
    if args.dry:
        return 0

    if STATE_PATH.exists():
        state = STATE_PATH.read_text().split()
        if state and state[0] == today:
            print(f"[tweet] {today} 已发过(state={STATE_PATH})— 跳过")
            return 0

    creds = json.loads(CREDS_PATH.read_text())
    for attempt in (1, 2):
        try:
            tweet_id = post_tweet(text, out, creds)
            break
        except Exception as e:  # noqa: BLE001 — journal 里要看全部失败形态
            print(f"[tweet] 第 {attempt} 次发布失败: {e}", file=sys.stderr)
            if attempt == 1:
                print(f"[tweet] {RETRY_DELAY_S}s 后重试一次…", file=sys.stderr)
                time.sleep(RETRY_DELAY_S)
    else:
        print("[tweet] 两次均失败 — 放弃(Release 不受影响)", file=sys.stderr)
        return 1

    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(f"{today} {tweet_id}\n")
    print(f"[tweet] 已发布: https://x.com/harrystep153131/status/{tweet_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
